export enum TestConstant {
  authToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkNoYXRSb2xlcy1zeXN0ZW0tdXNlciIsInRzIjoxNjg0MTIyMjg0OTk4LCJpYXQiOjE2ODQxMjIyODR9.4tP1DAuwntARWYOTjN1LPdWD0xq9JMyQ_I9-rqubXec',
}
